Update github-actions.yml

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -73,8 +73,6 @@ jobs:
                 run_pid=$!
                 
                 strace_log=$CINTENT_LOGS/strace.$timestamp
-                start_time=$SECONDS
-                timeout_time=60
                 ( 
                 sudo strace \
                 -e decode-fds=path \
@@ -87,9 +85,20 @@ jobs:
                 -Y \
                 -z
                 ) &
-                cat /proc/$run_pid/status | grep -oP "(?<=TracerPid:).*"
-                sleep 1
-                cat /proc/$run_pid/status | grep -oP "(?<=TracerPid:).*"
+                start_time=$SECONDS
+                timeout_time=60
+                tracer_pid=$(cat /proc/$run_pid/status | grep -oP "(?<=TracerPid:).*")
+                current_time=$(($SECONDS - $start_time))
+                until [[ "$tracer_pid" -ne 0 || "$current_time" -gt "$timeout_time" ]]; do
+                  sleep 1
+                  tracer_pid=$(cat /proc/$run_pid/status | grep -oP "(?<=TracerPid:).*")
+                  current_time=$(($SECONDS - $start_time))
+                done
+                if [[ "$tracer_pid" -eq 0 ]]; then
+                  echo "strace failed to start!" 1>&2
+                  exit 1
+                fi
+                
                 kill -CONT $run_pid
                 wait $run_pid
             else
